### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RehmatpalSingh**
Some cool changes to Readme by DuskyElf.

### CODE REVIEW

**Comment by SidisLiveYT** [comment]
> Some cool changes to Readme by DuskyElf.

I liked it But the thing is it is a framework and npm package , so your 
 Readme is not valid for it

**Comment by RehmatpalSingh** [comment]
No worries tho... I understand that

**Comment by RehmatpalSingh** [comment]
bye

**Comment by SidisLiveYT** [comment]
> No worries tho... I understand that

Zeon will udpate the Code as there are many typing errors

**Pull request closed without merging**
